# Generated by Django 4.2.2 on 2023-06-28 09:44

from django.db import migrations, models
import django.db.models.deletion
import fills.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBind',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_id', models.BigIntegerField()),
                ('data_name', models.CharField(max_length=255)),
                ('column_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataDefine',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=128)),
                ('data_group_id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataParameter',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('param_rule_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('expressions', models.CharField(max_length=512)),
                ('data_define_group_id', models.BigIntegerField()),
                ('data_bind_group_id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataValueList',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_id', models.BigIntegerField()),
                ('value_list', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FillingRequirement',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255)),
                ('remark', models.TextField(null=True)),
                ('file_id', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('start_line', models.PositiveIntegerField()),
                ('line_number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenerateRule',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_name', models.CharField(max_length=128)),
                ('function_name', models.CharField(max_length=255)),
                ('fill_order', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenerateRuleParameter',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required', models.BooleanField()),
                ('default_value', models.CharField(max_length=255, null=True)),
                ('need_outside_data', models.BooleanField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.generaterule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColumnRule',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_id', models.BigIntegerField()),
                ('data_param_id', models.BigIntegerField()),
                ('column_name', models.CharField(max_length=255)),
                ('column_type', models.CharField(max_length=128)),
                ('associated_of', models.BooleanField(default=False)),
                ('filling_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.fillingrequirement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
