# Generated by Django 4.1 on 2023-07-01 09:51

import django.db.models.deletion
from django.db import migrations, models

import fills.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnRule',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column_name', models.CharField(max_length=255)),
                ('column_type', models.CharField(max_length=128)),
                ('associated_of', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('data_type', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FillingRequirement',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255)),
                ('remark', models.TextField(blank=True)),
                ('file_id', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('start_line', models.PositiveIntegerField()),
                ('line_number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenerateRule',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_name', models.CharField(max_length=128)),
                ('function_name', models.CharField(max_length=255)),
                ('fill_order', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenerateRuleParameter',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required', models.BooleanField()),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('need_outside_data', models.BooleanField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.generaterule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataSetValue',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.TextField()),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataSetDefine',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataSetBind',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column_name', models.CharField(max_length=255)),
                ('data_name', models.CharField(max_length=255)),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataParameter',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('expressions', models.CharField(blank=True, max_length=512)),
                ('data_set_id', models.BigIntegerField(blank=True, null=True)),
                ('column_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.columnrule')),
                ('param_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.generateruleparameter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='columnrule',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.fillingrequirement'),
        ),
        migrations.AddField(
            model_name='columnrule',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.generaterule'),
        ),
    ]
