# Generated by Django 4.1 on 2023-07-05 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnrule',
            name='column_type',
            field=models.CharField(choices=[('string', '字符串'), ('number', '数值'), ('boolean', '布尔值')], max_length=128),
        ),
        migrations.AlterField(
            model_name='dataparameter',
            name='value',
            field=models.CharField(blank=True, default=str, max_length=255),
        ),
        migrations.AlterField(
            model_name='datasetdefine',
            name='data_type',
            field=models.CharField(choices=[('string', '字符串'), ('number', '数值'), ('boolean', '布尔值')], max_length=255),
        ),
        migrations.AlterField(
            model_name='fillingrequirement',
            name='line_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='支持填充行数在1到200之间'), django.core.validators.MaxValueValidator(200, message='支持填充行数在1到200之间')]),
        ),
        migrations.AlterField(
            model_name='fillingrequirement',
            name='original_filename',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='必须为.xlsx格式的excel文件', regex='.xlsx$')]),
        ),
        migrations.AlterField(
            model_name='fillingrequirement',
            name='start_line',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='起始行在1到42之间'), django.core.validators.MaxValueValidator(42, message='起始行在1到42之间')]),
        ),
        migrations.AlterField(
            model_name='generateruleparameter',
            name='data_type',
            field=models.CharField(choices=[('string', '字符串'), ('number', '数值'), ('boolean', '布尔值')], max_length=255),
        ),
    ]
