# Generated by Django 4.1 on 2023-07-09 11:31

from django.db import migrations, models
import fills.models


class Migration(migrations.Migration):

    dependencies = [
        ('fills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigIntegerField(default=fills.models.gen_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('requirement_id', models.BigIntegerField(verbose_name='关联填充要求')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('file_id', models.CharField(max_length=255, verbose_name='对象存储ID')),
                ('filename', models.CharField(max_length=255, verbose_name='原始文件名')),
            ],
            options={
                'verbose_name': '文件记录',
                'verbose_name_plural': '文件记录',
                'db_table': 'file_record',
            },
        ),
    ]
