# Generated by Django 4.1 on 2023-06-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataparameter',
            name='data_bind_group_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataparameter',
            name='data_define_group_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataparameter',
            name='expressions',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='dataparameter',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='generateruleparameter',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
