# Generated by Django 4.1 on 2023-07-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fills', '0002_filerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateruleparameter',
            name='hints',
            field=models.CharField(blank=True, max_length=512, verbose_name='输入提示'),
        ),
        migrations.AlterField(
            model_name='generateruleparameter',
            name='description',
            field=models.CharField(max_length=512, verbose_name='描述'),
        ),
    ]
