# Generated by Django 4.1 on 2023-07-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fills', '0002_filerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateruleparameter',
            name='hints',
            field=models.CharField(blank=True, max_length=512, verbose_name='输入提示'),
        ),
        migrations.AlterField(
            model_name='dataparameter',
            name='data_set_id',
            field=models.BigIntegerField(default=None, null=True, verbose_name='关联数据集'),
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='file_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='对象存储ID'),
        ),
        migrations.AlterField(
            model_name='fillingrequirement',
            name='file_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='对象存储ID'),
        ),
        migrations.AlterField(
            model_name='generaterule',
            name='function_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='函数名'),
        ),
        migrations.AlterField(
            model_name='generaterule',
            name='rule_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='规则名'),
        ),
        migrations.AlterField(
            model_name='generateruleparameter',
            name='description',
            field=models.CharField(max_length=512, verbose_name='描述'),
        ),
        migrations.AddConstraint(
            model_name='columnrule',
            constraint=models.UniqueConstraint(fields=('requirement_id', 'column_name'), name='unique_column_name'),
        ),
        migrations.AddConstraint(
            model_name='datasetbind',
            constraint=models.UniqueConstraint(fields=('column_name', 'data_name'), name='unique_data_attr_bind'),
        ),
        migrations.AddConstraint(
            model_name='datasetdefine',
            constraint=models.UniqueConstraint(fields=('data_set_id', 'name'), name='unique_data_attr_name'),
        ),
        migrations.AddConstraint(
            model_name='generateruleparameter',
            constraint=models.UniqueConstraint(fields=('rule_id', 'name'), name='unique_param_name'),
        ),
    ]
