# Generated by Django 4.1 on 2023-07-07 22:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fills', '0003_remove_dataset_data_type_datasetvalue_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnrule',
            name='associated_of',
            field=models.BooleanField(default=False, verbose_name='是否需要外部数据集'),
        ),
        migrations.AlterField(
            model_name='columnrule',
            name='column_name',
            field=models.CharField(max_length=8, validators=[django.core.validators.MaxLengthValidator(3, message='不要搞那么后面的列')], verbose_name='单元格列'),
        ),
        migrations.AlterField(
            model_name='columnrule',
            name='column_type',
            field=models.CharField(choices=[('string', '字符串'), ('number', '数值'), ('boolean', '布尔值')], max_length=64, verbose_name='单元格数据类型'),
        ),
        migrations.AlterField(
            model_name='columnrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='columnrule',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.fillingrequirement', verbose_name='关联填充要求'),
        ),
        migrations.AlterField(
            model_name='columnrule',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.generaterule', verbose_name='关联规则'),
        ),
        migrations.AlterField(
            model_name='columnrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='dataparameter',
            name='column_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.columnrule', verbose_name='关联列规则'),
        ),
        migrations.AlterField(
            model_name='dataparameter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dataparameter',
            name='data_set_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='关联数据集'),
        ),
        migrations.AlterField(
            model_name='dataparameter',
            name='expressions',
            field=models.CharField(blank=True, max_length=512, verbose_name='计算表达式'),
        ),
        migrations.AlterField(
            model_name='dataparameter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='参数名'),
        ),
        migrations.AlterField(
            model_name='dataparameter',
            name='param_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.generateruleparameter', verbose_name='关联参数'),
        ),
        migrations.AlterField(
            model_name='dataparameter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='dataparameter',
            name='value',
            field=models.CharField(blank=True, default=str, max_length=255, verbose_name='参数值'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='datasetbind',
            name='column_name',
            field=models.CharField(max_length=8, verbose_name='单元格列名'),
        ),
        migrations.AlterField(
            model_name='datasetbind',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='datasetbind',
            name='data_name',
            field=models.CharField(max_length=255, verbose_name='关联属性名'),
        ),
        migrations.AlterField(
            model_name='datasetbind',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.dataset', verbose_name='关联数据集'),
        ),
        migrations.AlterField(
            model_name='datasetbind',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='datasetdefine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='datasetdefine',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.dataset', verbose_name='关联数据集'),
        ),
        migrations.AlterField(
            model_name='datasetdefine',
            name='data_type',
            field=models.CharField(choices=[('string', '字符串'), ('number', '数值'), ('boolean', '布尔值')], max_length=255, verbose_name='数据类型'),
        ),
        migrations.AlterField(
            model_name='datasetdefine',
            name='name',
            field=models.CharField(max_length=255, verbose_name='属性名'),
        ),
        migrations.AlterField(
            model_name='datasetdefine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='datasetvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='datasetvalue',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.dataset', verbose_name='关联数据集'),
        ),
        migrations.AlterField(
            model_name='datasetvalue',
            name='data_type',
            field=models.CharField(choices=[('string', '字符串'), ('dict', '字典')], max_length=255, verbose_name='数据类型（字典或字符串）'),
        ),
        migrations.AlterField(
            model_name='datasetvalue',
            name='item',
            field=models.TextField(verbose_name='数据项'),
        ),
        migrations.AlterField(
            model_name='datasetvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='fillingrequirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='fillingrequirement',
            name='file_id',
            field=models.CharField(max_length=255, verbose_name='对象存储ID'),
        ),
        migrations.AlterField(
            model_name='fillingrequirement',
            name='line_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='支持填充行数在1到200之间'), django.core.validators.MaxValueValidator(200, message='支持填充行数在1到200之间')], verbose_name='结束行'),
        ),
        migrations.AlterField(
            model_name='fillingrequirement',
            name='original_filename',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='必须为.xlsx格式的excel文件', regex='.xlsx$')], verbose_name='原始文件名'),
        ),
        migrations.AlterField(
            model_name='fillingrequirement',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='fillingrequirement',
            name='start_line',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='起始行在1到42之间'), django.core.validators.MaxValueValidator(42, message='起始行在1到42之间')], verbose_name='起始行'),
        ),
        migrations.AlterField(
            model_name='fillingrequirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='fillingrequirement',
            name='username',
            field=models.CharField(max_length=255, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='generaterule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='generaterule',
            name='description',
            field=models.TextField(verbose_name='功能描述'),
        ),
        migrations.AlterField(
            model_name='generaterule',
            name='fill_order',
            field=models.PositiveIntegerField(verbose_name='填入顺序'),
        ),
        migrations.AlterField(
            model_name='generaterule',
            name='function_name',
            field=models.CharField(max_length=255, verbose_name='函数名'),
        ),
        migrations.AlterField(
            model_name='generaterule',
            name='rule_name',
            field=models.CharField(max_length=128, verbose_name='规则名'),
        ),
        migrations.AlterField(
            model_name='generaterule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='generateruleparameter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='generateruleparameter',
            name='data_type',
            field=models.CharField(choices=[('string', '字符串'), ('number', '数值'), ('boolean', '布尔值')], max_length=255, verbose_name='数据类型'),
        ),
        migrations.AlterField(
            model_name='generateruleparameter',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, verbose_name='默认值'),
        ),
        migrations.AlterField(
            model_name='generateruleparameter',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='generateruleparameter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='参数名'),
        ),
        migrations.AlterField(
            model_name='generateruleparameter',
            name='need_outside_data',
            field=models.BooleanField(verbose_name='是否需要外部数据'),
        ),
        migrations.AlterField(
            model_name='generateruleparameter',
            name='required',
            field=models.BooleanField(verbose_name='是否必填'),
        ),
        migrations.AlterField(
            model_name='generateruleparameter',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fills.generaterule', verbose_name='关联规则'),
        ),
        migrations.AlterField(
            model_name='generateruleparameter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
