@baseUrl=http://127.0.0.1:4200

# @name login
POST {{baseUrl}}/api/token HTTP/1.1
Content-Type: application/json

{"username": "jack", "password": "4321dcba"}

###
@token={{login.response.body.access}}

###
GET {{baseUrl}}/fills/columnRule
?requirementId=
&size=8 HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/fills/columnRule HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "requirement_id": 12348647260160,
    "rule_id": 4880372080640,
    "column_name": "EAE",
    "column_type": "string",
    "associated_of": false
}

###
GET {{baseUrl}}/fills/dataParameter
?columnRuleId=7019797061632
&size=8 HTTP/1.1
Authorization: Bearer {{token}}
