@baseUrl=http://127.0.0.1:4200

# @name login
POST {{baseUrl}}/api/token HTTP/1.1
Content-Type: application/json

{"username": "L", "password": "4321dcba"}

###
@token={{login.response.body.access}}


###
GET {{baseUrl}}/fills/dataSet
?size=8 HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/fills/dataSetDefine
?dataSetId=7016422940672
&size=8 HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/fills/dataSetValue
?dataSetId=7016422940672
&size=8 HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/fills/dataSetBind
?dataSetId=7016422940672
&size=8 HTTP/1.1
Authorization: Bearer {{token}}