@baseUrl=http://localhost:4200

# @name login
POST {{baseUrl}}/auth/token HTTP/1.1
Content-Type: application/json

{"username": "jack", "password": "4321dcba"}

###
@token={{login.response.body.access}}

###
GET {{baseUrl}}/fills/fileRecord
?username=jack
&size=8 HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/fills/fileRecord/12510258331648 HTTP/1.1
Authorization: Bearer {{token}}