@baseUrl=http://127.0.0.1:4200

# @name login
POST {{baseUrl}}/auth/token HTTP/1.1
Content-Type: application/json

{"username": "jack", "password": "4321dcba"}

###
@token={{login.response.body.access}}

###
GET {{baseUrl}}/fills/requirement
?size=8 HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/fills/requirement/12348647260160 HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/fills/requirement HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "jack",
    "remark": "哦吼",
    "file_id": "1",
    "original_filename": "abc885呵呵.xlsx",
    "start_line": 2,
    "line_number": 100
}

###
PUT {{baseUrl}}/fills/requirement/24761638166528 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "jack",
    "remark": "哦吼001",
    "file_id": "22啊21aa",
    "original_filename": "abc呵呵.xlsx",
    "start_line": 2,
    "line_number": 100
}

###
DELETE {{baseUrl}}/fills/requirement/16697376522240 HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/fills/upload HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

berhaments
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="工作簿1.xlsx"
Content-Type: text/sql

< D:/工作簿1.xlsx
------WebKitFormBoundary7MA4YWxkTrZu0gW--