@baseUrl=http://localhost:4200

# @name login
POST {{baseUrl}}/auth/token HTTP/1.1
Content-Type: application/json

{"username": "jack", "password": "4321dcba"}

###
@token={{login.response.body.access}}


###
GET {{baseUrl}}/user/jack HTTP/1.1
Authorization: Bearer {{token}}
